name: Manual Backup to S3

on:
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Create backup
        run: |
          TIMESTAMP=$(date +%Y-%m-%d_%H-%M-%S)
          REPO_NAME=${GITHUB_REPOSITORY##*/}
          zip -r "${REPO_NAME}_${TIMESTAMP}.zip" .

      - name: Upload to S3
        run: |
          TIMESTAMP=$(date +%Y-%m-%d_%H-%M-%S)
          REPO_NAME=${GITHUB_REPOSITORY##*/}
          aws s3 cp "${REPO_NAME}_${TIMESTAMP}.zip" "s3://${{ secrets.S3_BUCKET }}/${REPO_NAME}/${REPO_NAME}_${TIMESTAMP}.zip"
