name: Manual Backup to S3

on:
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Create temporary directory
        run: mkdir repo-backup

      - name: Clone repository with all branches
        run: |
          REPO_URL="https://github.com/${GITHUB_REPOSITORY}.git"
          cd repo-backup
          # Clone the bare repository
          git clone --mirror $REPO_URL .
          # Update all refs
          git fetch --all
          # Ensure we have all remote branches
          git remote update origin --prune

      - name: List all branches (for verification)
        run: |
          cd repo-backup
          echo "Available branches:"
          git branch -a

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Create and upload backup
        run: |
          TIMESTAMP=$(date +%Y-%m-%d_%H-%M-%S)
          REPO_NAME=${GITHUB_REPOSITORY##*/}
          cd repo-backup
          zip -r "../${REPO_NAME}_${TIMESTAMP}.zip" .
          cd ..
          aws s3 cp "${REPO_NAME}_${TIMESTAMP}.zip" "s3://${{ secrets.S3_BUCKET }}/${REPO_NAME}/${REPO_NAME}_${TIMESTAMP}.zip"
